// ============================================================
// SECTION: Demo Users
// ============================================================

export const demoUsers = [
  {
    id: 'student-1',
    email: 'student1@librarydemo.com',
    name: 'Alice Johnson',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    phone: '555-0101',
    address: '123 Student St, University City, UC 12345',
    joinDate: '2023-09-15',
    borrowingLimit: 5,
    preferredGenres: ['Fiction', 'Mystery', 'Sci-Fi'],
    preferencesSetup: true,
    status: 'active',
    password: 'Student123!',
  },
  {
    id: 'staff-1',
    email: 'staff1@librarydemo.com',
    name: 'Bob Smith',
    role: 'staff',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    phone: '555-0102',
    address: '456 Library Ave, Library City, LC 67890',
    joinDate: '2022-01-10',
    status: 'active',
    password: 'Staff123!',
  },
  {
    id: 'admin-1',
    email: 'admin1@librarydemo.com',
    name: 'Carol Davis',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    phone: '555-0103',
    address: '789 Admin Blvd, Admin City, AC 13579',
    joinDate: '2020-06-01',
    status: 'active',
    password: 'Admin123!',
  },
];

// ============================================================
// SECTION: Sample Books
// ============================================================

export const sampleBooks = [
  {
    id: 'book-1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    cover: 'https://covers.openlibrary.org/b/id/7725515-M.jpg',
    rating: 4.5,
    category: 'Fiction',
    availability: 3,
    totalCopies: 5,
    bookType: 'physical',
    description: 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.',
    publicationDate: '1925-04-10',
    publisher: 'Scribner',
    tags: ['classic', 'american', 'romance'],
    isbn: '978-0743273565',
  },
  {
    id: 'book-2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    cover: 'https://covers.openlibrary.org/b/id/3530539-M.jpg',
    rating: 4.8,
    category: 'Fiction',
    availability: 2,
    totalCopies: 4,
    bookType: 'physical',
    description: 'A gripping tale of racial injustice and childhood innocence in the American South.',
    publicationDate: '1960-07-11',
    publisher: 'J. B. Lippincott',
    tags: ['classic', 'coming-of-age', 'american'],
    isbn: '978-0061120084',
  },
  {
    id: 'book-3',
    title: '1984',
    author: 'George Orwell',
    cover: 'https://covers.openlibrary.org/b/id/7826177-M.jpg',
    rating: 4.3,
    category: 'Sci-Fi',
    availability: 1,
    totalCopies: 3,
    bookType: 'ebook',
    description: 'A dystopian novel depicting a totalitarian society and the dangers of authoritarianism.',
    publicationDate: '1949-06-08',
    publisher: 'Secker & Warburg',
    tags: ['dystopian', 'sci-fi', 'political'],
    isbn: '978-0451524935',
  },
  {
    id: 'book-4',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    cover: 'https://covers.openlibrary.org/b/id/10197821-M.jpg',
    rating: 4.6,
    category: 'Non-fiction',
    availability: 4,
    totalCopies: 6,
    bookType: 'ebook',
    description: 'A sweeping history of humankind from the Stone Age to the modern era.',
    publicationDate: '2014-09-04',
    publisher: 'Harville Secker',
    tags: ['history', 'anthropology', 'non-fiction'],
    isbn: '978-0062316097',
  },
  {
    id: 'book-5',
    title: 'The Catcher in the Rye',
    author: 'J. D. Salinger',
    cover: 'https://covers.openlibrary.org/b/id/5102922-M.jpg',
    rating: 4.1,
    category: 'Fiction',
    availability: 2,
    totalCopies: 4,
    bookType: 'physical',
    description: 'A controversial coming-of-age novel following teenager Holden Caulfield.',
    publicationDate: '1951-07-16',
    publisher: 'Little, Brown',
    tags: ['coming-of-age', 'american', 'classic'],
    isbn: '978-0316769174',
  },
  {
    id: 'book-6',
    title: 'Atomic Habits',
    author: 'James Clear',
    cover: 'https://covers.openlibrary.org/b/id/9279902-M.jpg',
    rating: 4.7,
    category: 'Academic',
    availability: 5,
    totalCopies: 7,
    bookType: 'ebook',
    description: 'A practical guide to building good habits and breaking bad ones through small, incremental changes.',
    publicationDate: '2018-10-16',
    publisher: 'Avery',
    tags: ['self-help', 'productivity', 'psychology'],
    isbn: '978-0735211292',
  },
  {
    id: 'book-7',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    cover: 'https://covers.openlibrary.org/b/id/10238162-M.jpg',
    rating: 4.4,
    category: 'Mystery',
    availability: 3,
    totalCopies: 5,
    bookType: 'physical',
    description: 'A gripping psychological thriller about a woman who shoots her husband and then never speaks again.',
    publicationDate: '2019-02-05',
    publisher: 'Celadon Books',
    tags: ['thriller', 'mystery', 'psychological'],
    isbn: '978-1250295522',
  },
  {
    id: 'book-8',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    cover: 'https://covers.openlibrary.org/b/id/7950485-M.jpg',
    rating: 4.6,
    category: 'Romance',
    availability: 2,
    totalCopies: 4,
    bookType: 'physical',
    description: 'A timeless romance novel exploring social class, marriage, and personal growth.',
    publicationDate: '1813-01-28',
    publisher: 'T. Egerton',
    tags: ['romance', 'classic', 'british'],
    isbn: '978-0141439518',
  },
  {
    id: 'book-9',
    title: 'Dune',
    author: 'Frank Herbert',
    cover: 'https://covers.openlibrary.org/b/id/5105855-M.jpg',
    rating: 4.5,
    category: 'Sci-Fi',
    availability: 3,
    totalCopies: 5,
    bookType: 'ebook',
    description: 'An epic science fiction novel set on the desert planet Arrakis, filled with politics, religion, and ecology.',
    publicationDate: '1965-06-01',
    publisher: 'Chilton Books',
    tags: ['sci-fi', 'epic', 'worldbuilding'],
    isbn: '978-0441172719',
  },
  {
    id: 'book-10',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    cover: 'https://covers.openlibrary.org/b/id/9292193-M.jpg',
    rating: 4.2,
    category: 'Academic',
    availability: 4,
    totalCopies: 6,
    bookType: 'physical',
    description: 'A transformative guide to living in the present moment and achieving spiritual enlightenment.',
    publicationDate: '1997-09-16',
    publisher: 'New World Library',
    tags: ['spirituality', 'self-help', 'mindfulness'],
    isbn: '978-1577314806',
  },
];

// ============================================================
// SECTION: Sample Borrowing Requests
// ============================================================

export const sampleBorrowingRequests = [
  {
    id: 'req-1',
    userId: 'student-1',
    bookId: 'book-1',
    type: 'borrow',
    status: 'approved',
    requestDate: '2024-03-10',
    dueDate: '2024-03-24',
  },
  {
    id: 'req-2',
    userId: 'student-1',
    bookId: 'book-4',
    type: 'borrow',
    status: 'pending',
    requestDate: '2024-03-20',
  },
  {
    id: 'req-3',
    userId: 'student-1',
    bookId: 'book-6',
    type: 'reserve',
    status: 'pending',
    requestDate: '2024-03-22',
  },
  {
    id: 'req-4',
    userId: 'student-1',
    bookId: 'book-2',
    type: 'borrow',
    status: 'completed',
    requestDate: '2024-02-15',
    dueDate: '2024-03-01',
    returnDate: '2024-02-28',
  },
  {
    id: 'req-5',
    userId: 'student-1',
    bookId: 'book-3',
    type: 'borrow',
    status: 'completed',
    requestDate: '2024-01-20',
    dueDate: '2024-02-03',
    returnDate: '2024-02-05',
  },
];

// ============================================================
// SECTION: Sample Notifications
// ============================================================

export const sampleNotifications = [
  {
    id: 'notif-1',
    userId: 'student-1',
    title: 'Book Request Approved',
    message: 'Your request for "The Great Gatsby" has been approved. Please pick it up within 3 days.',
    type: 'success',
    read: false,
    createdAt: '2024-03-20T10:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'student-1',
    title: 'Due Date Reminder',
    message: '"The Great Gatsby" is due in 2 days. Please return it to avoid late fees.',
    type: 'warning',
    read: false,
    createdAt: '2024-03-22T14:15:00Z',
  },
  {
    id: 'notif-3',
    userId: 'student-1',
    title: 'Book Available',
    message: 'The book you reserved "Atomic Habits" is now available for pickup.',
    type: 'info',
    read: true,
    createdAt: '2024-03-18T09:00:00Z',
  },
];

// ============================================================
// SECTION: AI Recommendations
// ============================================================

export const aiRecommendations = [
  {
    bookId: 'book-6',
    reason: 'Based on your reading history of self-improvement books',
    score: 0.92,
  },
  {
    bookId: 'book-4',
    reason: 'Popular among readers who liked "1984"',
    score: 0.87,
  },
  {
    bookId: 'book-9',
    reason: 'Recommended for sci-fi enthusiasts',
    score: 0.84,
  },
];
